socketServerUrl: ws://localhost:8081/websocket/main

#redis
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    max-active: 5
    max-wait: 1000
    max-idle: 8
    min-idle: 3
    timeout: 60000

  application:
    name: sale-data-mainclient
  security:
    user:
      name: user
      password: password

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8281/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh,health,info
